### ISSUE TITLE
Logging out with backpack equipped corrupts the character file

### ISSUE THREAD

**Issue by Emrik-North** [VMP-Valheim/Back_packs#1]
I started with a clean game, installed Jotunn and HookGenPatcher, then the BackPacks.dll. I go into game, create a new female character and log into a world. Spawn in CapeIronBackpack, equip it, log out, and I notice the character has been replaced with a naked white bald man. It doesn't happen unless I have equipped a backpack (maybe it happens if I just have it in my inventory, but I can't remember checking that).

**Comment by sbtoonz** [comment]
https://github.com/VMP-Valheim/Back_packs/releases/tag/0.0.5
